### PR TITLE
Add Smart Access Flow

### PR DESCRIPTION
**Pull request by theanandankit**

### CODE REVIEW

**Comment by theanandankit** [comment]
@ibacher i have made the all changes required to communicate with SMART-on-FHIR module. PTAL

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
@theanandankit This looks good to me! Thanks for all the work on this! You ready to mark this PR as no longer being a draft?

**Comment by theanandankit** [comment]
@ibacher thanks, I think now we can merge this PR.

**Comment by theanandankit** [comment]
@ibacher i think now we can merge this PR.

**Pull request merged**
